# Generated by Django 4.1.1 on 2023-01-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "male"), ("Female", "Female")],
                max_length=100,
            ),
        ),
    ]
