# Generated by Django 4.1.1 on 2023-01-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="poc_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
