# Generated by Django 4.1.1 on 2022-12-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_postcertificate_certificate_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="signature",
            field=models.ImageField(blank=True, null=True, upload_to="certificates"),
        ),
    ]
