# Generated by Django 4.1.1 on 2022-12-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_postcertificate_certificate_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="c_type",
            field=models.CharField(
                choices=[
                    ("Posts", "Posts"),
                    ("Likes", "Likes"),
                    ("Followers", "Followers"),
                ],
                max_length=100,
            ),
        ),
    ]
