# Generated by Django 4.1.1 on 2022-12-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_certificate_c_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcertificate",
            name="follow",
        ),
    ]
