# Generated by Django 4.1.1 on 2022-12-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_remove_postcertificate_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcertificate",
            name="certificate_image",
            field=models.ImageField(blank=True, null=True, upload_to="certificates"),
        ),
    ]
