# Generated by Django 4.1.1 on 2022-12-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_alter_postcertificate_certificate_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcertificate",
            name="certificate_image",
            field=models.ImageField(blank=True, null=True, upload_to="usercirtificate"),
        ),
    ]
