# Generated by Django 4.1.1 on 2022-12-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_postcertificate_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcertificate",
            name="follow",
        ),
    ]
