# Generated by Django 4.1.1 on 2023-01-02 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("post", "0010_remove_postcertificate_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcertificate",
            name="follow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.followrequest",
            ),
        ),
    ]
