# Generated by Django 4.1.1 on 2023-01-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_postcertificate_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="media"),
        ),
    ]
